# Generated by Django 6.0.3 on 2026-05-08 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(help_text='Heart Rate in BPM')),
                ('blood_oxygen', models.IntegerField(help_text='Blood Oxygen SpO2 %')),
                ('steps', models.IntegerField(default=0, help_text='Daily steps count')),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vitals Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
